tap "beeftornado/rmtree"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "martido/brew-graph"
tap "puma/puma"
tap "wallix/awless"
tap "wata727/tflint"
tap "weihanglo/sfz", "https://github.com/weihanglo/sfz.git"
brew "ansible"
brew "autojump"
brew "awscli"
brew "bat"
brew "cmake"
brew "cocoapods"
brew "consul"
brew "coreutils"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "exa"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "ghostscript"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "gnupg"
brew "git-secret"
brew "glide"
brew "gnu-sed"
brew "gradle"
brew "htop"
brew "httpie"
brew "hub"
brew "hwloc"
brew "usbmuxd", args: ["HEAD"]
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "ios-deploy"
brew "jq"
brew "kubernetes-helm"
brew "libmicrohttpd"
brew "libuv"
brew "mackup"
brew "mas"
brew "mosh"
brew "ncdu"
brew "opencc"
brew "pinentry-mac"
brew "postgresql", restart_service: true
brew "prettyping"
brew "pyenv"
brew "rbenv"
brew "ripgrep"
brew "skaffold"
brew "terraform"
brew "tflint"
brew "tmux"
brew "tokei"
brew "tree"
brew "vim"
brew "watchman"
brew "wget"
brew "yarn"
brew "heroku/brew/heroku-node"
brew "heroku/brew/heroku"
brew "puma/puma/puma-dev"
brew "weihanglo/sfz/sfz"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "cheatsheet"
cask "daisydisk"
cask "dash"
cask "deckset"
cask "docker"
cask "dotnet-sdk"
cask "dropbox"
cask "firefox"
cask "font-firacode-nerd-font"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "font-lato"
cask "font-montserrat"
cask "font-noto-sans-cjk-tc"
cask "font-noto-serif-cjk-tc"
cask "font-roboto"
cask "font-roboto-slab"
cask "fork"
cask "gitup"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "hyper"
cask "iina"
cask "java8"
cask "jetbrains-toolbox"
cask "keka"
cask "keycastr"
cask "launchcontrol"
cask "moom"
cask "ngrok"
cask "notion"
cask "paragon-ntfs"
cask "protonvpn"
cask "react-native-debugger"
cask "robo-3t"
cask "screens-connect"
cask "setapp"
cask "sketch"
cask "slack"
cask "soundflower"
cask "soundflowerbed"
cask "spotify"
cask "standard-notes"
cask "station"
cask "teamviewer"
cask "telegram-desktop"
cask "tunnelblick"
cask "typora"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
cask "zeplin"
cask "zoomus"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Drafts", id: 1435957248
mas "Evernote", id: 406056744
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "RunCat", id: 1429033973
mas "Simplenote", id: 692867256
mas "Spark", id: 1176895641
mas "Things", id: 904280696
mas "Xcode", id: 497799835
