tap "beeftornado/rmtree"
tap "cloudflare/cloudflare"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/core"
tap "homebrew/services"
tap "puma/puma"
tap "robotsandpencils/made"
tap "wata727/tflint"
tap "weihanglo/sfz", "https://github.com/weihanglo/sfz.git"
brew "aria2"
brew "autoconf"
brew "automake"
brew "awscli"
brew "bandwhich"
brew "bash"
brew "cocoapods"
brew "coreutils"
brew "diff-so-fancy"
brew "direnv"
brew "gnutls"
brew "ffmpeg"
brew "fzf"
brew "git"
brew "git-extras"
brew "git-flow"
brew "gnupg", link: false
brew "git-secret"
brew "gnu-sed"
brew "graphviz"
brew "htop"
brew "httpie"
brew "hwloc"
brew "hyperfine"
brew "imagemagick"
brew "ispell"
brew "jq"
brew "libuv"
brew "lnav"
brew "mackup"
brew "mas"
brew "mosh"
brew "nasm"
brew "ncdu"
brew "nmap"
brew "nss"
brew "opencc"
brew "parallel"
brew "pinentry-mac"
brew "prettyping"
brew "pstree"
brew "shellcheck"
brew "stow"
brew "utf8proc"
brew "wget"
brew "wrk"
brew "zsh"
brew "cloudflare/cloudflare/cloudflared"
brew "robotsandpencils/made/xcodes"
brew "weihanglo/sfz/sfz"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "chromium"
cask "daisydisk"
cask "discord"
cask "firefox"
cask "font-jetbrains-mono-nerd-font"
cask "gpg-suite-no-mail"
cask "iina"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "keyboardcleantool"
cask "monitorcontrol"
cask "moom"
cask "parallels"
cask "protonvpn"
cask "rancher"
cask "signal"
cask "spotify"
cask "squirrel"
cask "steam"
cask "syncthing"
cask "telegram"
cask "visual-studio-code"
mas "Amphetamine", id: 937984704
mas "DevCleaner", id: 1388020431
mas "Disk Speed Test", id: 425264550
mas "Drafts", id: 1435957248
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pocket", id: 568494494
mas "Reeder", id: 1529448980
mas "RunCat", id: 1429033973
mas "Streaks", id: 963034692
mas "Things", id: 904280696
mas "Unsplash Wallpapers", id: 1284863847
mas "Welly", id: 1521402269
mas "WireGuard", id: 1451685025
