tap "beeftornado/rmtree"
tap "derailed/k9s"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "martido/brew-graph"
tap "puma/puma"
tap "wallix/awless"
tap "wata727/tflint"
tap "weihanglo/sfz", "https://github.com/weihanglo/sfz.git"
brew "ansible"
brew "autojump"
brew "awscli"
brew "bat"
brew "cmake"
brew "cocoapods"
brew "consul"
brew "coreutils"
brew "go"
brew "dep"
brew "diff-so-fancy"
brew "doctl"
brew "drone-cli"
brew "exa"
brew "faas-cli"
brew "ffmpeg"
brew "fish"
brew "fzf"
brew "ghostscript"
brew "git"
brew "git-extras"
brew "git-lfs"
brew "gnupg"
brew "git-secret"
brew "glide"
brew "gnu-sed"
brew "gradle"
brew "graphviz"
brew "helm"
brew "htop"
brew "httpie"
brew "hub"
brew "hwloc"
brew "libimobiledevice", args: ["HEAD"]
brew "ideviceinstaller"
brew "imagemagick"
brew "ios-deploy"
brew "jq"
brew "kustomize"
brew "libmicrohttpd"
brew "libusbmuxd", args: ["HEAD"]
brew "libuv"
brew "mackup"
brew "mas"
brew "mkcert"
brew "mosh"
brew "mysql"
brew "ncdu"
brew "nss"
brew "opencc"
brew "pinentry-mac"
brew "pipenv"
brew "postgresql", restart_service: true
brew "prettyping"
brew "pyenv"
brew "ripgrep"
brew "skaffold"
brew "starship"
brew "terraform"
brew "tflint"
brew "tmux"
brew "tokei"
brew "tree"
brew "vim"
brew "watch"
brew "watchman"
brew "wget"
brew "yarn"
brew "derailed/k9s/k9s"
brew "heroku/brew/heroku-node"
brew "heroku/brew/heroku"
brew "puma/puma/puma-dev"
brew "weihanglo/sfz/sfz"
cask "1password"
cask "alfred"
cask "appcleaner"
cask "cheatsheet"
cask "dash"
cask "docker"
cask "dropbox"
cask "firefox"
cask "font-firacode-nerd-font"
cask "font-fontawesome"
cask "font-hack-nerd-font"
cask "font-lato"
cask "font-montserrat"
cask "font-noto-sans-cjk-tc"
cask "font-noto-serif-cjk-tc"
cask "font-roboto"
cask "font-roboto-slab"
cask "fork"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "hyper"
cask "java8"
cask "jetbrains-toolbox"
cask "keka"
cask "keyboardcleantool"
cask "moom"
cask "ngrok"
cask "notion"
cask "parallels"
cask "protonvpn"
cask "robo-3t"
cask "screens-connect"
cask "setapp"
cask "sketch"
cask "slack"
cask "soundflower"
cask "soundflowerbed"
cask "spotify"
cask "steam"
cask "syncthing"
cask "telegram-desktop"
cask "termius"
cask "tunnelblick"
cask "visual-studio-code"
cask "zoomus"
mas "Affinity Designer", id: 824171161
mas "Affinity Photo", id: 824183456
mas "Amphetamine", id: 937984704
mas "Drafts", id: 1435957248
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "RunCat", id: 1429033973
mas "Spark", id: 1176895641
mas "Things", id: 904280696
