" Generated by vim-plug
" 2022年01月08日 (週六) 00時48分34秒
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Colorizer'].commit = '826d5691ac7d36589591314621047b1b9d89ed34'
silent! let g:plugs['NrrwRgn'].commit = 'be7f06308bddd493d436372ee71d6b366af97fbb'
silent! let g:plugs['YouCompleteMe'].commit = 'c0e82e91a4ca780dad67f7bb8f6067a1cc11f580'
silent! let g:plugs['csv.vim'].commit = '9ab092187a7046a8d0eedc7fbbce8fac38d10563'
silent! let g:plugs['editorconfig-vim'].commit = '3078cd10b28904e57d878c0d0dab42aa0a9fdc89'
silent! let g:plugs['emmet-vim'].commit = 'def5d57a1ae5afb1b96ebe83c4652d1c03640f4d'
silent! let g:plugs['file-line'].commit = '559088afaf10124ea663ee0f4f73b1de48fb1632'
silent! let g:plugs['fzf'].commit = '9cb7a364a31bdb882d873807774bdcf6fad0c9e4'
silent! let g:plugs['fzf.vim'].commit = 'd6aa21476b2854694e6aa7b0941b8992a906c5ec'
silent! let g:plugs['i3config.vim'].commit = '5c753c56c033d3b17e5005a67cdb9653bbb88ba7'
silent! let g:plugs['indentLine'].commit = '5617a1cf7d315e6e6f84d825c85e3b669d220bfa'
silent! let g:plugs['nerdcommenter'].commit = '9fffd4c022da39a324a2eee2a0939db66db7c553'
silent! let g:plugs['rainbow'].commit = 'c18071e5c7790928b763c2e88c487dfc93d84a15'
silent! let g:plugs['splitjoin.vim'].commit = '0f45bfd7d6a8acb7d6ac126001a27190851bf3f5'
silent! let g:plugs['syntastic'].commit = '2c4b33f6e6679fb5f3824d9cd38d4813c71a19a3'
silent! let g:plugs['targets.vim'].commit = '8d6ff2984cdfaebe5b7a6eee8f226a6dd1226f2d'
silent! let g:plugs['vim-airline'].commit = '332d44948a3c737272172d0eae0bf5b940e72459'
silent! let g:plugs['vim-airline-themes'].commit = '97cf3e6e638f936187d5f6e9b5eb1bdf0a4df256'
silent! let g:plugs['vim-better-whitespace'].commit = 'c5afbe91d29c5e3be81d5125ddcdc276fd1f1322'
silent! let g:plugs['vim-easymotion'].commit = 'd75d9591e415652b25d9e0a3669355550325263d'
silent! let g:plugs['vim-endwise'].commit = '4289889a2622f9bc7c594a6dd79763781f63dfb5'
silent! let g:plugs['vim-fugitive'].commit = 'b1c3cdffc94c2cbe48777db5cf8bc9156b17d070'
silent! let g:plugs['vim-gitgutter'].commit = '256702dd1432894b3607d3de6cd660863b331818'
silent! let g:plugs['vim-go'].commit = 'a319aaf6bf652dadb197807e4629ff5b1750a17b'
silent! let g:plugs['vim-json'].commit = '3727f089410e23ae113be6222e8a08dd2613ecf2'
silent! let g:plugs['vim-jsx'].commit = '8879e0d9c5ba0e04ecbede1c89f63b7a0efa24af'
silent! let g:plugs['vim-markdown'].commit = '8e5d86f7b85234d3d1b4207dceebc43a768ed5d4'
silent! let g:plugs['vim-multiple-cursors'].commit = '6456718e1d30b42c04b920c5413ca44f68f08759'
silent! let g:plugs['vim-polyglot'].commit = 'c96947b1c64c56f70125a9bac9c006f69e45d5d3'
silent! let g:plugs['vim-ragtag'].commit = 'b8966c4f6503a8baaec39e17bd0bf38b2aadc9b2'
silent! let g:plugs['vim-rails'].commit = '3bac0233a49d2a00805c66bf17d3e2ea114b05d1'
silent! let g:plugs['vim-repeat'].commit = '24afe922e6a05891756ecf331f39a1f6743d3d5a'
silent! let g:plugs['vim-surround'].commit = 'aeb933272e72617f7c4d35e1f003be16836b948d'
silent! let g:plugs['vim-test'].commit = 'c44be6765edb81834797e66ad206f83e190bdd49'
silent! let g:plugs['vim-unimpaired'].commit = 'e4006d68cd4f390efef935bc09be0ce3bd022e72'

PlugUpdate!

