#!/usr/bin/env bash
# shellcheck shell=bash
# ref: https://github.com/leftwm/leftwm/blob/4f765b4ba148c94b9ff6942ed12818b51b516589/themes/basic_polybar/up

SCRIPTPATH="$( cd "$(dirname "$0")" || exit ; pwd -P )"
export SCRIPTPATH

# down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# boot picom or compton if it exists
if [ -x "$(command -v picom)" ]; then
  picom &> /dev/null &
elif [ -x "$(command -v compton)" ]; then
  compton &> /dev/null &
fi

# set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

index=0
monitors="$(polybar -m | sed s/:.*//)"
# shellcheck disable=2034
leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width x y
do
  (( indextemp=index+1 ))
  monitor=$(sed "$indextemp!d" <<<"$monitors")
  barname="mainbar$index"
  monitor=$monitor offset=$x width=$width polybar -c "$SCRIPTPATH"/polybar.config $barname &> /dev/null &
  (( index=indextemp ))
done

# vim: ft=bash sw=2
